Use the 1Password SSH agent

diff --git a/install b/install
--- a/install
+++ b/install
@@ -44,6 +44,13 @@ else
     brew install mas
 fi
 
+if [[ -d /Applications/1Password.app ]]; then
+    echo "1Password already installed."
+else
+    echo "Installing 1Password..."
+    brew install --cask 1password
+fi
+
 if hash op &>/dev/null; then
     echo "1Password CLI already installed."
 else
@@ -51,16 +58,20 @@ else
     brew install --cask 1password-cli
 fi
 
-if [[ -f "$HOME/.config/op/config" ]]; then
-    echo "1Password CLI already configured."
-else
-    echo "Configuring 1Password CLI..."
-    eval "$(op account add --address my.1password.com --shorthand my --signin)"
+echo "First, add your personal 1Password account to the app, then enable the following options in the preferences:"
+echo
+echo "    - Developer > 1Password SSH Agent > Use the SSH agent"
+echo "    - Developer > 1Password CLI 2 > Biometric unlock for 1Password CLI"
+echo
 
-    if [[ ! -f "$HOME/.config/op/config" ]]; then
-        echo "1Password configuration failed."
-        exit 1
-    fi
+open "/Applications/1Password.app"
+
+read -p "Have you configured the specified options? [yn] " -n 1 -r
+echo
+if [[ ! $REPLY =~ ^[Yy]$ ]]
+then
+    echo "Unable to continue without configuring 1Password."
+    exit 1
 fi
 
 until op account get --account my &>/dev/null
@@ -70,14 +81,14 @@ do
     eval $(op signin --account=my)
 done
 
-OP_USER_ID="$(cat ~/.config/op/config | jq --raw-output '.accounts[] | select(.shorthand == "my").userUUID')"
-OP_SESSION="OP_SESSION_$OP_USER_ID"
-
-echo "1Password CLI session detected."
-echo "To persist the 1Password CLI session, run the following command:"
-echo
-printf "    export %s=%q\n" "$OP_SESSION" "${!OP_SESSION}"
-echo
+if [[ -f "$HOME/.ssh/config" ]]; then
+    echo "SSH already configured."
+else
+    echo "Temporarily configuring SSH to use the 1Password SSH agent..."
+    mkdir -p "$HOME/.ssh"
+    echo 'Host *
+    IdentityAgent "~/Library/Group Containers/2BUA8C4S2C.com.1password/t/agent.sock"' > "$HOME/.ssh/config"
+fi
 
 # Waiting on https://github.com/mas-cli/mas/issues/417
 # if mas account &>/dev/null; then
@@ -122,7 +133,7 @@ if [[ -d "$DOTFILES_PATH" ]]; then
     popd &>/dev/null
 else
     echo "Cloning $GH_USER/dotfiles..."
-    git clone "https://github.com/$GH_USER/dotfiles.git" "$DOTFILES_PATH"
+    git clone "git@github.com:$GH_USER/dotfiles.git" "$DOTFILES_PATH"
 fi
 
 if [[ -e "$HOME/dotfiles" ]]; then
